name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Deploy application
        run: |
          echo "Building application..."
          echo "Running deployment..."
<<<<<<< HEAD
          echo "Application deployed successfully!"
=======
          echo "Application deployed successfully!"
>>>>>>> 9b707297ab0d87291724590706339270f7d2621e
